/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_peergos_crypto_NativeTweetNacl */

#ifndef _Included_org_peergos_crypto_NativeTweetNacl
#define _Included_org_peergos_crypto_NativeTweetNacl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_peergos_crypto_NativeTweetNacl
 * Method:    ld32
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_peergos_crypto_NativeTweetNacl_ld32
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
