/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class peergos_server_crypto_JniTweetNacl */

#ifndef _Included_peergos_server_crypto_JniTweetNacl
#define _Included_peergos_server_crypto_JniTweetNacl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    crypto_box_keypair
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_crypto_1box_1keypair
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    crypto_box_open
 * Signature: ([B[BJ[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_crypto_1box_1open
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    crypto_box
 * Signature: ([B[BJ[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_crypto_1box
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    crypto_sign_open
 * Signature: ([BJ[BJ[B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_crypto_1sign_1open
  (JNIEnv *, jclass, jbyteArray, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    crypto_sign
 * Signature: ([BJ[BJ[B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_crypto_1sign
  (JNIEnv *, jclass, jbyteArray, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    crypto_sign_keypair
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_crypto_1sign_1keypair
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    crypto_secretbox_open
 * Signature: ([B[BJ[B[B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_crypto_1secretbox_1open
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    crypto_secretbox
 * Signature: ([B[BJ[B[B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_crypto_1secretbox
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jlong, jbyteArray, jbyteArray);

/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    crypto_scalarmult_base
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_crypto_1scalarmult_1base
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     peergos_server_crypto_JniTweetNacl
 * Method:    ld32
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_peergos_server_crypto_JniTweetNacl_ld32
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
